[package]
name = "riko-tools"
version.workspace = true
edition.workspace = true

[dependencies]
smol_str.workspace = true
riko-core.workspace = true
tokio.workspace = true
tokio-util.workspace = true
parking_lot.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
ignore.workspace = true
regex.workspace = true
similar.workspace = true

[dev-dependencies]
tempfile.workspace = true
