[workspace]
resolver = "2"
members = [
    "crates/*",
    "apps/*",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
riko-utils = { path = "crates/riko-utils" }
riko-core = { path = "crates/riko-core" }
riko-llm = { path = "crates/riko-llm" }
riko-context = { path = "crates/riko-context" }
riko-tools = { path = "crates/riko-tools" }
riko-config = { path = "crates/riko-config" }
riko-agent = { path = "crates/riko-agent" }
riko-engine = { path = "crates/riko-engine" }

# Http
reqwest = { version = "0.13.3", features = ["json", "stream", "rustls"], default-features = false }

# Async
futures = "0.3.32"
async-stream = "0.3.6"
tokio = { version = "1.52.3", features = ["sync", "macros", "rt", "fs", "process", "time", "io-util"] }
tokio-util  = { version = "0.7.18"}

# Serialization
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.150"
toml = "1.1.2+spec-1.1.0"

# JSON Schema generation (for Tool input structs)
schemars = "1.2.1"

# Structure
bytes = { version = "1.11.1", features = ["serde"] }
smol_str = { version = "0.3.6", features = ["serde"] }
parking_lot = "0.12.5"

# FS
ignore = "0.4.25"
regex = "1.12.3"
similar = "3.1.1"

# Error handling
thiserror = "2.0.18"
anyhow = "1.0.102"

# TUI / CLI
ratatui = { version = "0.30.0", features = ["unstable-rendered-line-info"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
clap = { version = "4.6.1", features = ["derive"] }

# MISC
uuid = { version = "1.23.3", features = ["v4", "serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
tempfile = "3.27.0"
