[package]
name = "riko-llm"
version.workspace = true
edition.workspace = true

[dependencies]
riko-core.workspace = true
smol_str.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-util.workspace = true
futures.workspace = true
async-stream.workspace = true
parking_lot.workspace = true
tokio.workspace = true
